version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    # networks:
    #   - internal
      #   - web
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  whoami:
    image: jwilder/whoami
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=whoami.ewekombucha.ga
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.ewekombucha.ga
      - LETSENCRYPT_EMAIL=luandro@gmail.com
  api:
    build: ./api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=jwtsecret123
      - PRISMA_SECRET=mysecret123
      - PRISMA_URL=https://us1.prisma.sh/luandro-93a3b2/periodico/dev
      - NODE_ENV=production
      - VIRTUAL_HOST=api.revistappc.com
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=api.revistappc.com
      - LETSENCRYPT_EMAIL=luandro@gmail.com
  admin:
    build: ./admin
    restart: always
    volumes:
      - ./admin:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    ports:
      - "3005:3005"
    command: "npm start"
    environment:
      - API_HOST=https://api.revistappc.com
      - NODE_ENV=production
      - VIRTUAL_HOST=admin.revistappc.com
      - VIRTUAL_PORT=3005
      - LETSENCRYPT_HOST=admin.revistappc.com
      - LETSENCRYPT_EMAIL=luandro@gmail.com
  journal:
    build: ./journal
    restart: always
    volumes:
      - ./journal:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    ports:
      - "3001:3001"
    command: "npm start"
    environment:
      - API_HOST=https://api.revistappc.com
      - NODE_ENV=production
      - VIRTUAL_HOST=periodico2.revistappc.com
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=periodico2.revistappc.com
      - LETSENCRYPT_EMAIL=luandro@gmail.com