version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - internal
      #   - web
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  whoami:
    image: jwilder/whoami
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=whoami.ewekombucha.ga
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.ewekombucha.ga
      - LETSENCRYPT_EMAIL=luandro@gmail.com
    # networks:
    #   - web
      # - internal
  postgres:
    image: postgres
    restart: always
    environment:
      # NETWORK_ACCESS: internal
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - internal
  prisma:
    image: prismagraphql/prisma:1.20.1
    restart: always
    ports:
    - "4466:4466"
    environment:
      VIRTUAL_HOST: prisma.ewekombucha.ga
      VIRTUAL_PORT: 4466
      LETSENCRYPT_HOST: prisma.ewekombucha.ga
      LETSENCRYPT_EMAIL: luandro@gmail.com
      # NETWORK_ACCESS: internal
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            rawAccess: true
    depends_on:
      - postgres
    networks:
      - internal
networks:
  internal:
    external:
      name: internal
volumes: 
  certs:
  html:
  vhostd:
  postgres:
